version: 2

builds:
  - main: ./cmd/tonrelay/
    binary: tonrelay
    ldflags:
      - -s -w -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

release:
  github:
    owner: TONresistor
    name: tonrelay
